import type { User } from "@db/users/types";

export const database: User[] = [
  {
    id: 1,
    cpf: "12345678909",
    name: "John Doe",
    email: "don85@johnson.com",
    profile: "Administrador",
    active: true,
    pointSaleId: 1,
  },
  {
    id: 2,
    cpf: "98765432100",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    profile: "Gerente de vendas",
    active: true,
    pointSaleId: 2,
  },
  {
    id: 3,
    cpf: "12312312312",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    profile: "Vendedor",
    active: true,
    pointSaleId: 3,
  },
  {
    id: 4,
    cpf: "32132132132",
    name: "Bob Brown",
    email: "bob.brown@example.com",
    profile: "Vendedor",
    active: false,
    pointSaleId: 4,
  },
  {
    id: 5,
    cpf: "45645645645",
    name: "Charlie Davis",
    email: "charlie.davis@example.com",
    profile: "Administrador",
    active: true,
    pointSaleId: 5,
  },
  {
    id: 6,
    cpf: "65465465465",
    name: "Diana Evans",
    email: "diana.evans@example.com",
    profile: "Vendedor",
    active: true,
    pointSaleId: 6,
  },
  {
    id: 7,
    cpf: "78978978978",
    name: "Eve Foster",
    email: "eve.foster@example.com",
    profile: "Vendedor",
    active: true,
    pointSaleId: 7,
  },
  {
    id: 8,
    cpf: "85285285285",
    name: "Frank Green",
    email: "frank.green@example.com",
    profile: "Gerente de vendas",
    active: true,
    pointSaleId: 8,
  },
  {
    id: 9,
    cpf: "15915915915",
    name: "Grace Harris",
    email: "grace.harris@example.com",
    profile: "Administrador",
    active: true,
    pointSaleId: 9,
  },
  {
    id: 10,
    cpf: "95195195195",
    name: "Henry Jackson",
    email: "henry.jackson@example.com",
    profile: "Vendedor",
    active: true,
    pointSaleId: 10,
  },
  {
    id: 11,
    cpf: "75375375375",
    name: "Ivy King",
    email: "ivy.king@example.com",
    profile: "Vendedor",
    active: false,
    pointSaleId: 11,
  },
  {
    id: 12,
    cpf: "35735735735",
    name: "Jack Lee",
    email: "jack.lee@example.com",
    profile: "Gerente de vendas",
    active: true,
    pointSaleId: 12,
  },
  {
    id: 13,
    cpf: "25825825825",
    name: "Karen Martinez",
    email: "karen.martinez@example.com",
    profile: "Administrador",
    active: true,
    pointSaleId: 13,
  },
  {
    id: 14,
    cpf: "85285285285",
    name: "Leo Nelson",
    email: "leo.nelson@example.com",
    profile: "Vendedor",
    active: true,
    pointSaleId: 14,
  },
  {
    id: 15,
    cpf: "45612378945",
    name: "Mia Owens",
    email: "mia.owens@example.com",
    profile: "Vendedor",
    active: false,
    pointSaleId: 15,
  },
  {
    id: 16,
    cpf: "65432198765",
    name: "Noah Perez",
    email: "noah.perez@example.com",
    profile: "Vendedor",
    active: true,
    pointSaleId: 16,
  },
  {
    id: 17,
    cpf: "74185296374",
    name: "Olivia Quinn",
    email: "olivia.quinn@example.com",
    profile: "Administrador",
    active: true,
    pointSaleId: 17,
  },
  {
    id: 18,
    cpf: "96325874196",
    name: "Paul Roberts",
    email: "paul.roberts@example.com",
    profile: "Vendedor",
    active: true,
    pointSaleId: 18,
  },
  {
    id: 19,
    cpf: "14725836914",
    name: "Quinn Scott",
    email: "quinn.scott@example.com",
    profile: "Vendedor",
    active: false,
    pointSaleId: 19,
  },
  {
    id: 20,
    cpf: "36914725836",
    name: "Rachel Taylor",
    email: "rachel.taylor@example.com",
    profile: "Vendedor",
    active: true,
    pointSaleId: 20,
  },
];
