import { PointOfSale } from "@/plugins/fake-api/handlers/points-of-sale/types";

export const database: PointOfSale[] = [
  {
    id: 1,
    cnpj: "00.000.000/0001-01",
    companyName: "Company 1",
    fantasyName: "Fantasy 1",
    contact: "1111111111",
    email: "email1@example.com",
    active: true,
    stateRegistration: "001",
    municipalRegistration: "001",
    companyId: 1,
    address: {
      street: "Street 1",
      number: "1",
      neighborhood: "Neighborhood 1",
      city: {
        id: 1,
        name: "São Paulo",
      },
      state: {
        id: 1,
        name: "São Paulo",
        abbreviation: "SP",
      },
      zipCode: "01000-000",
    },
  },
  {
    id: 2,
    cnpj: "00.000.000/0001-02",
    companyName: "Company 2",
    fantasyName: "Fantasy 2",
    contact: "2222222222",
    email: "email2@example.com",
    active: true,
    stateRegistration: "002",
    municipalRegistration: "002",
    companyId: 2,
    address: {
      street: "Street 2",
      number: "2",
      neighborhood: "Neighborhood 2",
      city: {
        id: 2,
        name: "Rio de Janeiro",
      },
      state: {
        id: 2,
        name: "Rio de Janeiro",
        abbreviation: "RJ",
      },
      zipCode: "20000-000",
    },
  },
  {
    id: 3,
    cnpj: "00.000.000/0001-03",
    companyName: "Company 3",
    fantasyName: "Fantasy 3",
    contact: "3333333333",
    email: "email3@example.com",
    active: true,
    stateRegistration: "003",
    municipalRegistration: "003",
    companyId: 3,
    address: {
      street: "Street 3",
      number: "3",
      neighborhood: "Neighborhood 3",
      city: {
        id: 3,
        name: "Belo Horizonte",
      },
      state: {
        id: 3,
        name: "Minas Gerais",
        abbreviation: "MG",
      },
      zipCode: "30000-000",
    },
  },
  {
    id: 4,
    cnpj: "00.000.000/0001-04",
    companyName: "Company 4",
    fantasyName: "Fantasy 4",
    contact: "4444444444",
    email: "email4@example.com",
    active: true,
    stateRegistration: "004",
    municipalRegistration: "004",
    companyId: 4,
    address: {
      street: "Street 4",
      number: "4",
      neighborhood: "Neighborhood 4",
      city: {
        id: 4,
        name: "Porto Alegre",
      },
      state: {
        id: 4,
        name: "Rio Grande do Sul",
        abbreviation: "RS",
      },
      zipCode: "90000-000",
    },
  },
  {
    id: 5,
    cnpj: "00.000.000/0001-05",
    companyName: "Company 5",
    fantasyName: "Fantasy 5",
    contact: "5555555555",
    email: "email5@example.com",
    active: true,
    stateRegistration: "005",
    municipalRegistration: "005",
    companyId: 5,
    address: {
      street: "Street 5",
      number: "5",
      neighborhood: "Neighborhood 5",
      city: {
        id: 5,
        name: "Curitiba",
      },
      state: {
        id: 5,
        name: "Paraná",
        abbreviation: "PR",
      },
      zipCode: "80000-000",
    },
  },
  {
    id: 6,
    cnpj: "00.000.000/0001-06",
    companyName: "Company 6",
    fantasyName: "Fantasy 6",
    contact: "6666666666",
    email: "email6@example.com",
    active: true,
    stateRegistration: "006",
    municipalRegistration: "006",
    companyId: 6,
    address: {
      street: "Street 6",
      number: "6",
      neighborhood: "Neighborhood 6",
      city: {
        id: 6,
        name: "Salvador",
      },
      state: {
        id: 6,
        name: "Bahia",
        abbreviation: "BA",
      },
      zipCode: "40000-000",
    },
  },
  {
    id: 7,
    cnpj: "00.000.000/0001-07",
    companyName: "Company 7",
    fantasyName: "Fantasy 7",
    contact: "7777777777",
    email: "email7@example.com",
    active: true,
    stateRegistration: "007",
    municipalRegistration: "007",
    companyId: 7,
    address: {
      street: "Street 7",
      number: "7",
      neighborhood: "Neighborhood 7",
      city: {
        id: 7,
        name: "Fortaleza",
      },
      state: {
        id: 7,
        name: "Ceará",
        abbreviation: "CE",
      },
      zipCode: "60000-000",
    },
  },
  {
    id: 8,
    cnpj: "00.000.000/0001-08",
    companyName: "Company 8",
    fantasyName: "Fantasy 8",
    contact: "8888888888",
    email: "email8@example.com",
    active: true,
    stateRegistration: "008",
    municipalRegistration: "008",
    companyId: 8,
    address: {
      street: "Street 8",
      number: "8",
      neighborhood: "Neighborhood 8",
      city: {
        id: 8,
        name: "Brasília",
      },
      state: {
        id: 8,
        name: "Distrito Federal",
        abbreviation: "DF",
      },
      zipCode: "70000-000",
    },
  },
  {
    id: 9,
    cnpj: "00.000.000/0001-09",
    companyName: "Company 9",
    fantasyName: "Fantasy 9",
    contact: "9999999999",
    email: "email9@example.com",
    active: true,
    stateRegistration: "009",
    municipalRegistration: "009",
    companyId: 9,
    address: {
      street: "Street 9",
      number: "9",
      neighborhood: "Neighborhood 9",
      city: {
        id: 9,
        name: "Recife",
      },
      state: {
        id: 9,
        name: "Pernambuco",
        abbreviation: "PE",
      },
      zipCode: "50000-000",
    },
  },
  {
    id: 10,
    cnpj: "00.000.000/0001-10",
    companyName: "Company 10",
    fantasyName: "Fantasy 10",
    contact: "1010101010",
    email: "email10@example.com",
    active: true,
    stateRegistration: "0010",
    municipalRegistration: "0010",
    companyId: 10,
    address: {
      street: "Street 10",
      number: "10",
      neighborhood: "Neighborhood 10",
      city: {
        id: 10,
        name: "Manaus",
      },
      state: {
        id: 10,
        name: "Amazonas",
        abbreviation: "AM",
      },
      zipCode: "69000-000",
    },
  },
  {
    id: 11,
    cnpj: "00.000.000/0001-11",
    companyName: "Company 11",
    fantasyName: "Fantasy 11",
    contact: "1111111111",
    email: "email11@example.com",
    active: true,
    stateRegistration: "011",
    municipalRegistration: "021",
    companyId: 11,
    address: {
      street: "Street 11",
      number: "11",
      neighborhood: "Neighborhood 11",
      city: {
        id: 11,
        name: "Belém",
      },
      state: {
        id: 11,
        name: "Pará",
        abbreviation: "PA",
      },
      zipCode: "66000-000",
    },
  },
  {
    id: 12,
    cnpj: "00.000.000/0001-12",
    companyName: "Company 12",
    fantasyName: "Fantasy 12",
    contact: "1212121212",
    email: "email12@example.com",
    active: true,
    stateRegistration: "012",
    municipalRegistration: "012",
    companyId: 12,
    address: {
      street: "Street 12",
      number: "12",
      neighborhood: "Neighborhood 12",
      city: {
        id: 12,
        name: "Goiânia",
      },
      state: {
        id: 12,
        name: "Goiás",
        abbreviation: "GO",
      },
      zipCode: "74000-000",
    },
  },
  {
    id: 13,
    cnpj: "00.000.000/0001-13",
    companyName: "Company 13",
    fantasyName: "Fantasy 13",
    contact: "1313131313",
    email: "email13@example.com",
    active: true,
    stateRegistration: "013",
    municipalRegistration: "013",
    companyId: 13,
    address: {
      street: "Street 13",
      number: "13",
      neighborhood: "Neighborhood 13",
      city: {
        id: 13,
        name: "Campinas",
      },
      state: {
        id: 13,
        name: "São Paulo",
        abbreviation: "SP",
      },
      zipCode: "13000-000",
    },
  },
  {
    id: 14,
    cnpj: "00.000.000/0001-14",
    companyName: "Company 14",
    fantasyName: "Fantasy 14",
    contact: "1414141414",
    email: "email14@example.com",
    active: true,
    stateRegistration: "014",
    municipalRegistration: "014",
    companyId: 14,
    address: {
      street: "Street 14",
      number: "14",
      neighborhood: "Neighborhood 14",
      city: {
        id: 14,
        name: "São Luís",
      },
      state: {
        id: 14,
        name: "Maranhão",
        abbreviation: "MA",
      },
      zipCode: "65000-000",
    },
  },
  {
    id: 15,
    cnpj: "00.000.000/0001-15",
    companyName: "Company 15",
    fantasyName: "Fantasy 15",
    contact: "1515151515",
    email: "email15@example.com",
    active: true,
    stateRegistration: "015",
    municipalRegistration: "015",
    companyId: 15,
    address: {
      street: "Street 15",
      number: "15",
      neighborhood: "Neighborhood 15",
      city: {
        id: 15,
        name: "Natal",
      },
      state: {
        id: 15,
        name: "Rio Grande do Norte",
        abbreviation: "RN",
      },
      zipCode: "59000-000",
    },
  },
  {
    id: 16,
    cnpj: "00.000.000/0001-16",
    companyName: "Company 16",
    fantasyName: "Fantasy 16",
    contact: "1616161616",
    email: "email16@example.com",
    active: true,
    stateRegistration: "016",
    municipalRegistration: "016",
    companyId: 16,
    address: {
      street: "Street 16",
      number: "16",
      neighborhood: "Neighborhood 16",
      city: {
        id: 16,
        name: "João Pessoa",
      },
      state: {
        id: 16,
        name: "Paraíba",
        abbreviation: "PB",
      },
      zipCode: "58000-000",
    },
  },
  {
    id: 17,
    cnpj: "00.000.000/0001-17",
    companyName: "Company 17",
    fantasyName: "Fantasy 17",
    contact: "1717171717",
    email: "email17@example.com",
    active: true,
    stateRegistration: "017",
    municipalRegistration: "017",
    companyId: 17,
    address: {
      street: "Street 17",
      number: "17",
      neighborhood: "Neighborhood 17",
      city: {
        id: 17,
        name: "Maceió",
      },
      state: {
        id: 17,
        name: "Alagoas",
        abbreviation: "AL",
      },
      zipCode: "57000-000",
    },
  },
  {
    id: 18,
    cnpj: "00.000.000/0001-18",
    companyName: "Company 18",
    fantasyName: "Fantasy 18",
    contact: "1818181818",
    email: "email18@example.com",
    active: true,
    stateRegistration: "018",
    municipalRegistration: "018",
    companyId: 18,
    address: {
      street: "Street 18",
      number: "18",
      neighborhood: "Neighborhood 18",
      city: {
        id: 18,
        name: "Aracaju",
      },
      state: {
        id: 18,
        name: "Sergipe",
        abbreviation: "SE",
      },
      zipCode: "49000-000",
    },
  },
  {
    id: 19,
    cnpj: "00.000.000/0001-19",
    companyName: "Company 19",
    fantasyName: "Fantasy 19",
    contact: "1919191919",
    email: "email19@example.com",
    active: true,
    stateRegistration: "019",
    municipalRegistration: "019",
    companyId: 19,
    address: {
      street: "Street 19",
      number: "19",
      neighborhood: "Neighborhood 19",
      city: {
        id: 19,
        name: "Teresina",
      },
      state: {
        id: 19,
        name: "Piauí",
        abbreviation: "PI",
      },
      zipCode: "64000-000",
    },
  },
  {
    id: 20,
    cnpj: "00.000.000/0001-20",
    companyName: "Company 20",
    fantasyName: "Fantasy 20",
    contact: "2020202020",
    email: "email20@example.com",
    active: true,
    stateRegistration: "020",
    municipalRegistration: "020",
    companyId: 20,
    address: {
      street: "Street 20",
      number: "20",
      neighborhood: "Neighborhood 20",
      city: {
        id: 20,
        name: "Florianópolis",
      },
      state: {
        id: 20,
        name: "Santa Catarina",
        abbreviation: "SC",
      },
      zipCode: "88000-000",
    },
  },
];
